name: treenix_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  home_widget: ^0.7.0
  shared_preferences: ^2.3.5

  google_sign_in: ^7.2.0
  http: ^1.5.0
  url_launcher: ^6.3.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
